#!/bin/bash

# docker stop v_api
# docker stop v_app
# docker stop v_phpmyadmin

docker stop v_next
docker stop v_mysql
docker stop v_nginx

echo 'y' | docker system prune

sh run dev

docker exec -it v_next sh -c 'npm run prisma:deploy'
