CREATE DATABASE IF NOT EXISTS `v_api_main`;
GRANT ALL ON `v_api_main`.* TO 'v_api_user'@'%';

REVOKE ALL PRIVILEGES ON  *.* FROM 'v_api_user'@'%';
REVOKE GRANT OPTION ON  *.* FROM 'v_api_user'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, ALTER,
CREATE TEMPORARY TABLES,

CREATE VIEW, EVENT, TRIGGER, SHOW VIEW,

CREATE ROUTINE, ALTER ROUTINE, EXECUTE
ON *.* TO 'v_api_user'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;